import { redirect } from "next/navigation";
import { LordsHall, type HallData } from "../../components/LordsHall";

/** Dev-only fixture for Lord's Hall UX + edge-case loops. */
const MOCK: HallData = {
  court: {
    id: "c1",
    slug: "meridian",
    name: "House Meridian",
    theme: "neon",
    widget: "playlist",
    tagline: "Bass for the loyal.",
  },
  lord: {
    id: "lord1",
    name: "Lady Meridian",
    avatarUrl: null,
    xUsername: "meridian",
    followers: 128,
  },
  season: {
    id: "s1",
    title: "Season of the Booth",
    targetReplies: 60,
    targetReposts: 20,
    targetMentions: 15,
    startsAt: new Date().toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21).toISOString(),
  },
  scoreboard: [
    {
      userId: "lord1",
      name: "Lady Meridian",
      avatarUrl: null,
      xUsername: "meridian",
      rank: "duke",
      role: "lord",
      standing: 100,
      replies: 18,
      reposts: 6,
      mentions: 4,
    },
    {
      userId: "v1",
      name: "Ser Kael",
      avatarUrl: null,
      xUsername: "kael",
      rank: "count",
      role: "vassal",
      standing: 72,
      replies: 42,
      reposts: 14,
      mentions: 9,
    },
    {
      userId: "v2",
      name: "Rowan",
      avatarUrl: null,
      xUsername: "rowan",
      rank: "baron",
      role: "vassal",
      standing: 41,
      replies: 21,
      reposts: 8,
      mentions: 3,
    },
    {
      userId: "v3",
      name: "New Blood",
      avatarUrl: null,
      xUsername: null,
      rank: "serf",
      role: "vassal",
      standing: 0,
      replies: 2,
      reposts: 0,
      mentions: 0,
    },
  ],
  leaderboard: [
    {
      userId: "lord1",
      name: "Lady Meridian",
      avatarUrl: null,
      xUsername: "meridian",
      rank: "duke",
      standing: 100,
      role: "lord",
    },
    {
      userId: "v1",
      name: "Ser Kael",
      avatarUrl: null,
      xUsername: "kael",
      rank: "count",
      standing: 72,
      role: "vassal",
    },
    {
      userId: "v2",
      name: "Rowan",
      avatarUrl: null,
      xUsername: null,
      rank: "baron",
      standing: 41,
      role: "vassal",
    },
    {
      userId: "v3",
      name: "New Blood",
      avatarUrl: null,
      xUsername: null,
      rank: "serf",
      standing: 0,
      role: "vassal",
    },
  ],
  playlist: [
    {
      id: "t1",
      title: "Red Banner",
      artist: "Court Tape",
      url: "https://open.spotify.com",
      by: "Ser Kael",
    },
    {
      id: "t2",
      title: "Midnight Fealty",
      artist: "Vassal Choir",
      url: "https://www.youtube.com",
      by: "Rowan",
    },
  ],
  moodboard: [
    {
      id: "p1",
      title: "Velvet cloak",
      imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400",
      sourceUrl: "https://www.pinterest.com",
      by: "Rowan",
    },
  ],
  viewer: {
    isMember: true,
    isLord: true,
    rank: "duke",
    standing: 100,
    userId: "lord1",
    isFollowingLord: false,
  },
};

export default function HallPreviewPage() {
  if (process.env.NODE_ENV === "production") redirect("/");
  return <LordsHall initial={MOCK} />;
}
